# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostFather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('marital', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
