# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='hostfather',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostfather',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='host_family.HostName'),
        ),
        migrations.AlterField(
            model_name='hostfather',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostfather',
            name='marital',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=8),
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='host_family.HostName')),
                ('name1', models.CharField(max_length=100)),
                ('gender1', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=2)),
                ('realtion1', models.CharField(max_length=50)),
                ('school1', models.CharField(max_length=100)),
                ('age1', models.CharField(max_length=3)),
                ('grade1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('gender2', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=2)),
                ('realtion2', models.CharField(max_length=50)),
                ('school2', models.CharField(max_length=100)),
                ('age2', models.CharField(max_length=3)),
                ('grade2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
                ('gender3', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=2)),
                ('realtion3', models.CharField(max_length=50)),
                ('school3', models.CharField(max_length=100)),
                ('age3', models.CharField(max_length=3)),
                ('grade3', models.CharField(max_length=100)),
                ('name4', models.CharField(max_length=100)),
                ('gender4', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=2)),
                ('realtion4', models.CharField(max_length=50)),
                ('school4', models.CharField(max_length=100)),
                ('age4', models.CharField(max_length=3)),
                ('grade4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='host_family.HostName')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('cellular', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HostMother',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='host_family.HostName')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('marital', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=8)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
