# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_family', '0002_auto_20161215_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional',
            old_name='realtion1',
            new_name='relation1',
        ),
        migrations.RenameField(
            model_name='additional',
            old_name='realtion2',
            new_name='relation2',
        ),
        migrations.RenameField(
            model_name='additional',
            old_name='realtion3',
            new_name='relation3',
        ),
        migrations.RenameField(
            model_name='additional',
            old_name='realtion4',
            new_name='relation4',
        ),
    ]
