# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('gender1', models.CharField(max_length=6)),
                ('relationship1', models.CharField(max_length=10)),
                ('school1', models.CharField(max_length=50)),
                ('age1', models.IntegerField(max_length=3)),
                ('grade1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('gender2', models.CharField(max_length=6)),
                ('relationship2', models.CharField(max_length=10)),
                ('school2', models.CharField(max_length=50)),
                ('age2', models.IntegerField(max_length=3)),
                ('grade2', models.CharField(max_length=50)),
                ('name3', models.CharField(max_length=50)),
                ('gender3', models.CharField(max_length=6)),
                ('relationship3', models.CharField(max_length=10)),
                ('school3', models.CharField(max_length=50)),
                ('age3', models.IntegerField(max_length=3)),
                ('grade3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.CharField(max_length=3)),
                ('when', models.CharField(max_length=255)),
                ('long', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentschool', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('grade', models.IntegerField(max_length=2)),
                ('gpa', models.CharField(max_length=3)),
                ('rank', models.CharField(max_length=50)),
                ('enrolldate', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('englishname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('birthplace', models.CharField(max_length=50)),
                ('apply_grade', models.CharField(max_length=2)),
                ('start_date', models.DateField()),
                ('visa', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=50)),
                ('i20', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slep', models.IntegerField()),
                ('slepdate', models.CharField(max_length=20)),
                ('toefl', models.IntegerField()),
                ('toefldate', models.CharField(max_length=20)),
                ('ssat', models.IntegerField()),
                ('ssatdate', models.CharField(max_length=20)),
                ('sat', models.IntegerField()),
                ('satdate', models.CharField(max_length=20)),
                ('act', models.IntegerField()),
                ('actdate', models.CharField(max_length=20)),
                ('other', models.IntegerField()),
                ('otherdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo')),
                ('address', models.CharField(max_length=200)),
                ('apt', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=10)),
                ('home_phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FatherInfo',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('marital', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='MARRIED', max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('day_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MotherInfo',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('marital', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='MARRIED', max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('day_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
