# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
