# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_stu', '0002_studentinfo_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('PRIVATE', 'Private'), ('OPEN-MINDED', 'Open-minded'), ('QUIET', 'Quiet'), ('ACTIVE', 'Active'), ('LIBERAL', 'Liberal'), ('OUTGOING', 'Outgoing'), ('SOCIAL', 'Social'), ('TRADITIONAL', 'Traditional'), ('OTHER', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_model', models.CharField(max_length=255)),
                ('dream_job', models.CharField(max_length=255)),
                ('interest', models.CharField(max_length=255)),
                ('hobby', models.CharField(max_length=255)),
                ('current_goal', models.CharField(max_length=255)),
                ('future_goal', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('music', models.CharField(max_length=255)),
                ('holiday', models.CharField(max_length=255)),
                ('animal', models.CharField(max_length=255)),
                ('movie', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('weekend', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('happiest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(blank=True)),
                ('question2', models.TextField(blank=True)),
                ('question3', models.TextField(blank=True)),
                ('question4', models.TextField(blank=True)),
                ('question5', models.TextField(blank=True)),
                ('question6', models.TextField(blank=True)),
                ('question7', models.TextField(blank=True)),
            ],
        ),
    ]
