# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_stu', '0003_multiplechoice_profile_shortanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswer',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question1',
            field=models.TextField(blank=True, help_text='Please share with us any academic or extracurricular                                                 activities, interests, or hobbies you are involved in or enjoy doing.'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question2',
            field=models.TextField(blank=True, help_text='What are some of your strengths and weaknesses?'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question3',
            field=models.TextField(blank=True, help_text='why are you interested in study aboard? What do you hope to                                                        gain from this experience?'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question4',
            field=models.TextField(blank=True, help_text='Describe one of the biggest challenges you had to face and                                                        what did your learn from this experience?'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question5',
            field=models.TextField(blank=True, help_text='Describe one person you admire and tell us why you admire                                                        him/her?'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question6',
            field=models.TextField(blank=True, help_text='where do you see yourself when you turn 21?'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='question7',
            field=models.TextField(blank=True, help_text='Write a brief self-introduction for your future host-family.'),
        ),
    ]
