# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_stu', '0004_auto_20161117_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='allergy',
            field=models.CharField(blank=True, choices=[('NUTS', 'Nuts'), ('MILK', 'Milk'), ('FISH', 'Fish'), ('VEGAN', 'Vegan'), ('WHEAT', 'Wheat'), ('OR', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='eat',
            field=models.CharField(blank=True, choices=[('FRUIT', 'Fruits'), ('CHICKEN', 'Chicken'), ('EGG', 'EGGS'), ('NOODLES', 'Noodles'), ('RICE', 'Rice'), ('MEAT', 'Red Meat'), ('VEG', 'Vegetables'), ('BREAD', 'Bread/Cereals'), ('SOY', 'Soy'), ('OR', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='not_eat',
            field=models.CharField(blank=True, choices=[('FRUIT', 'Fruits'), ('CHICKEN', 'Chicken'), ('EGG', 'EGGS'), ('NOODLES', 'Noodles'), ('RICE', 'Rice'), ('MEAT', 'Red Meat'), ('VEG', 'Vegetables'), ('BREAD', 'Bread/Cereals'), ('SOY', 'Soy'), ('OR', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='own_meal',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='pet',
            field=models.CharField(blank=True, choices=[('CAT', 'Like cats'), ('DOG', 'Like dogs'), ('ALL', 'Like all animals'), ('NO', "Don't like animals")], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='religious_service',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('DCARE', "Don't care")], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='restaurant',
            field=models.CharField(blank=True, choices=[('CH', 'Chinese'), ('KR', 'Korean'), ('JP', 'Japanese'), ('US', 'American'), ('MN', 'Mexican'), ('IY', 'Italian'), ('OR', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='smoke',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='smoke_free',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='special_diet',
            field=models.CharField(blank=True, choices=[('DAIRY', 'Dairy_Free'), ('GLUTEN', 'Gluten_Free'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OR', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='weekday_curfew',
            field=models.CharField(blank=True, choices=[('9', '9PM'), ('10', '10PM'), ('11', '11PM'), ('12', '12MM')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='weekend_curfew',
            field=models.CharField(blank=True, choices=[('11', '11PM'), ('12', '12AM'), ('1', '1AM'), ('2', '2AM')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='personality',
            field=models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative'), ('PRIVATE', 'Private'), ('OPEN-MINDED', 'Open-minded'), ('QUIET', 'Quiet'), ('ACTIVE', 'Active'), ('LIBERAL', 'Liberal'), ('OUTGOING', 'Outgoing'), ('SOCIAL', 'Social'), ('TRADITIONAL', 'Traditional'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
