# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_stu', '0005_auto_20161117_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='test',
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='age1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='age2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='age3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='gender1',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='gender2',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='gender3',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='grade1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='grade2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='grade3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='name1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='name2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='name3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='relationship1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='relationship2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='relationship3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='school1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='school2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalhousehold',
            name='school3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='apt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='day_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='education',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='employer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='marital',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='MARRIED', max_length=10),
        ),
        migrations.AlterField(
            model_name='fatherinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='history',
            name='long',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='when',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='day_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='education',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='employer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='marital',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='MARRIED', max_length=10),
        ),
        migrations.AlterField(
            model_name='motherinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='allergy',
            field=models.CharField(blank=True, choices=[('NUTS', 'Nuts'), ('MILK', 'Milk'), ('FISH', 'Fish'), ('VEGAN', 'Vegan'), ('WHEAT', 'Wheat'), ('OR', 'Other')], default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='eat',
            field=models.CharField(blank=True, choices=[('FRUIT', 'Fruits'), ('CHICKEN', 'Chicken'), ('EGG', 'EGGS'), ('NOODLES', 'Noodles'), ('RICE', 'Rice'), ('MEAT', 'Red Meat'), ('VEG', 'Vegetables'), ('BREAD', 'Bread/Cereals'), ('SOY', 'Soy'), ('OR', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='not_eat',
            field=models.CharField(blank=True, choices=[('FRUIT', 'Fruits'), ('CHICKEN', 'Chicken'), ('EGG', 'EGGS'), ('NOODLES', 'Noodles'), ('RICE', 'Rice'), ('MEAT', 'Red Meat'), ('VEG', 'Vegetables'), ('BREAD', 'Bread/Cereals'), ('SOY', 'Soy'), ('OR', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='own_meal',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='personality',
            field=models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative'), ('PRIVATE', 'Private'), ('OPEN-MINDED', 'Open-minded'), ('QUIET', 'Quiet'), ('ACTIVE', 'Active'), ('LIBERAL', 'Liberal'), ('OUTGOING', 'Outgoing'), ('SOCIAL', 'Social'), ('TRADITIONAL', 'Traditional'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='pet',
            field=models.CharField(blank=True, choices=[('CAT', 'Like cats'), ('DOG', 'Like dogs'), ('ALL', 'Like all animals'), ('NO', "Don't like animals")], max_length=3),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='religious_service',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('DCARE', "Don't care")], max_length=5),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='restaurant',
            field=models.CharField(blank=True, choices=[('CH', 'Chinese'), ('KR', 'Korean'), ('JP', 'Japanese'), ('US', 'American'), ('MN', 'Mexican'), ('IY', 'Italian'), ('OR', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='smoke',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='smoke_free',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='special_diet',
            field=models.CharField(blank=True, choices=[('DAIRY', 'Dairy_Free'), ('GLUTEN', 'Gluten_Free'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OR', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='weekday_curfew',
            field=models.CharField(blank=True, choices=[('9', '9PM'), ('10', '10PM'), ('11', '11PM'), ('12', '12MM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='weekend_curfew',
            field=models.CharField(blank=True, choices=[('11', '11PM'), ('12', '12AM'), ('1', '1AM'), ('2', '2AM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='shortanswer',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='englishname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='middlename',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='act',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='actdate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='current_stu.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='other',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='otherdate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='sat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='satdate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='slep',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='slepdate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='ssat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='ssatdate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefl',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefldate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
