# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_stu', '0006_auto_20161215_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='religious_service',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('DCARE', "Don't care")], max_length=10),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='weekday_curfew',
            field=models.CharField(blank=True, choices=[('9', '9PM'), ('10', '10PM'), ('11', '11PM'), ('12', '12MM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='weekend_curfew',
            field=models.CharField(blank=True, choices=[('11', '11PM'), ('12', '12AM'), ('1', '1AM'), ('2', '2AM')], max_length=5),
        ),
    ]
