# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential_stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselling',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='potential_stu.PotentialBasic')),
                ('semester', models.CharField(max_length=20)),
                ('apply_grade', models.IntegerField()),
                ('school1', models.CharField(max_length=50)),
                ('school2', models.CharField(max_length=50)),
                ('school3', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=200)),
                ('counsellor', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('fee', models.IntegerField()),
                ('pay_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='potentialbasic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
