# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potential_stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialStu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('parent_phone', models.CharField(blank=True, max_length=16)),
                ('parent_email', models.EmailField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, choices=[('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12)], max_length=2)),
                ('gpa', models.CharField(blank=True, max_length=5)),
                ('toefl', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='PotentialBasic',
        ),
        migrations.CreateModel(
            name='CounsellingInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='potential_stu.PotentialStu')),
                ('semester', models.CharField(max_length=20)),
                ('apply_grade', models.CharField(choices=[('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12)], max_length=2)),
                ('school1', models.CharField(blank=True, max_length=100)),
                ('school2', models.CharField(blank=True, max_length=100)),
                ('school3', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('counsellor', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=10)),
                ('fee', models.IntegerField(blank=True)),
                ('pay_date', models.DateField(blank=True)),
            ],
        ),
    ]
