# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potential_stu', '0002_auto_20161115_0535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counselling',
            new_name='CounsellingInfo',
        ),
        migrations.RenameModel(
            old_name='PotentialBasic',
            new_name='PotentialStu',
        ),
    ]
